[project]
name = "encode-httpx-learn"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "httpx[brotli,cli,http2,zstd]>=0.28.1",
]

[dependency-groups]
dev = [
    "ruff>=0.11.6",
    "ruff-lsp>=0.0.62",
]
